version: '3'
services:
  blue:
    build:
      context: ./blue
      dockerfile: Dockerfile
    container_name: blue_app
    ports:
      - "8081:80"

  green:
    build:
      context: ./green
      dockerfile: Dockerfile
    container_name: green_app
    ports:
      - "8082:80"